// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3sK8yiHf7wM4Rga9-W8izuKN48fSeibY',
    appId: '1:539167238693:web:e65923cfea3f386976edcc',
    messagingSenderId: '539167238693',
    projectId: 'ridenear-4ecf9',
    authDomain: 'ridenear-4ecf9.firebaseapp.com',
    storageBucket: 'ridenear-4ecf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB327FNhyk5atKy0MLDpJRYIdP6FdqrQ1g',
    appId: '1:539167238693:android:90e94a2cef152d2e76edcc',
    messagingSenderId: '539167238693',
    projectId: 'ridenear-4ecf9',
    storageBucket: 'ridenear-4ecf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJFBeJ31nv3Eexnw96ZHYZyjFeZm4XT4',
    appId: '1:539167238693:ios:fcee0c7c8f0ef89676edcc',
    messagingSenderId: '539167238693',
    projectId: 'ridenear-4ecf9',
    storageBucket: 'ridenear-4ecf9.firebasestorage.app',
    iosBundleId: 'com.example.ridenear',
  );
}
